import Head from "next/head"

export const Meta = ({title}) => {
  return (
    <>
     <Head>
         <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}

Meta.defaultProps={
  title:'SendAnywhere | Home'
}